routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('category', 'CategoryController');
    Route::resource('resort', 'ResortController', ['only' => ['show', 'index', 'destroy', 'update']]);
    Route::resource('event', 'EventController');
    Route::resource('tourist', 'TouristController');
    Route::resource('archive', 'ArchiveController');
    Route::resource('hotline', 'HotlineController', ['except' => ['show']]);
    Route::resource('profile', 'ProfileController');
    Route::resource('account', 'AccountController');
});

Route::group(['as' => 'owner.', 'prefix' => 'owner', 'namespace' => 'Owner', 'middleware' => ['auth', 'owner']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('resort', 'ResortController');
    Route::resource('image', 'ImageController');
    Route::post('image/remove','ImageController@fileDestroy')->name('image.remove');
    Route::post('image/upload/{image}','ImageController@upload')->name('image.upload');
    Route::resource('profile', 'ProfileController');
});

app/Http/Controllers/Admin/EventController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Event;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\DataTables;

class EventController extends Controller
{

    public function index()
    {
        $data = Event::latest()->get();

        return view('admin.event.index',[
            'data' => $data
        ]);
    }

    public function create()
    {
        return view('admin.event.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'date' => 'required',
            'description' => 'required',
        ]);

        $event = Event::create([
            'name' => $request->name,
            'address' => $request->address,
            'date' => $request->date,
            'description' => $request->description,
        ]);

        Toastr::success('Successfully Saved' ,'Success');
        return redirect()->route('admin.event.index');
    }

    public function show(Event $event)
    {
        return view('admin.event.show',[
            'event' => $event
        ]);
    }

    public function edit(Event $event)
    {
        return view('admin.event.edit',[
            'data' => $event
        ]);
    }

    public function update(Request $request, Event $event)
    {
        $event->update($request->all());

        Toastr::success('Successfully Updated' ,'Success');
        return redirect()->route('admin.event.index');
    }

    public function destroy(Event $event)
    {
        Event::destroy($event->id);
        Toastr::success('Successfully Deleted' ,'Success');
        return redirect()->route('admin.event.index');
    }
}

resources/views/admin/event/create.blade.php
@extends('layouts.backend.app')

@section('title', 'Create event')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.event.index') }}"><i class="material-icons">event</i>Event list</a></li>
                <li class="active"><i class="material-icons">create</i> Create event</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>CREATE EVENT</h2>
                    </div>
                    <div class="body">
                        <form id="event_form" action="{{ route('admin.event.store') }}" method="POST">
                            @csrf
                            <div class="row clearfix">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Event name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="event_form_name" name="name" placeholder="Event name" value="{{ old('name') }}" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Address</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="event_form_address" name="address" value="{{ old('address') }}" placeholder="Address">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Event date</label>
                                        <div class="form-line">
                                            <input type="date" class="form-control date" id="event_form_date" name="date" value="{{ old('date') }}" placeholder="Ex: mm-dd-yyyy">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="event_form_description">Description</label>
                                        <div class="form-line">
                                            <textarea class="form-control" rows="10" id="event_form_description" name="description" placeholder="Description">{{ old('description') }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <script>
        $('#event_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'address': {
                    required: true,
                },
                'date': {
                    required: true,
                },
                'description': {
                    required: true,
                },
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/event/edit.blade.php
@extends('layouts.backend.app')

@section('title', 'Create event')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.event.index') }}"><i class="material-icons">event</i>Event list</a></li>
                <li class="active"><i class="material-icons">create</i> Edit event</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>EDIT EVENT</h2>
                    </div>
                    <div class="body">
                        <form id="event_form" action="{{ route('admin.event.update', $data->id) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="row clearfix">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Event name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="event_form_name" name="name" placeholder="Event name"
                                                   value="{{ $data->name }}" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Address</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="event_form_address" name="address" placeholder="Address"
                                                   value="{{ $data->address }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Event date</label>
                                        <div class="form-line">
                                            <input type="date" class="form-control date" id="event_form_date" name="date" placeholder="Ex: mm-dd-yyyy"
                                                   value="{{ $data->date }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="event_form_description">Description</label>
                                        <div class="form-line">
                                            <textarea class="form-control" rows="10" id="event_form_description" name="description" placeholder="Description">{{ $data->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <script>
        $('#event_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'address': {
                    required: true,
                },
                'date': {
                    required: true,
                },
                'description': {
                    required: true,
                },
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/event/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Event')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.event.index') }}"><i class="material-icons">event</i>Event list</a></li>
            </ol>
        </div>

        <!-- Content -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            EVENTS LIST
                            <label class="label label-info">{{ $data->count() }}</label>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="{{ route('admin.event.create') }}" class="btn bg-teal waves-effect">
                                    ADD EVENT
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover eventTable">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Date</th>
                                    <th>Updated at</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($data as $key => $datum)
                                    <tr>
                                        <td>{{ $datum->name }}</td>
                                        <td>{{ $datum->address }}</td>
                                        <td width="100px">{{ date('M d, Y', strtotime($datum->date)) }}</td>
                                        <td width="170px">{{ date('M d, Y h:i:s A', strtotime($datum->updated_at)) }}</td>
                                        <td width="150px">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Action <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="{{ route('admin.event.show', $datum->id) }}">
                                                            <i class="material-icons">remove_red_eye</i>View
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{{ route('admin.event.edit', $datum->id) }}">
                                                            <i class="material-icons">edit</i>Edit
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:void(0)" onclick="deleteData({{ $datum->id }})">
                                                            <i class="material-icons">delete</i>Delete
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <form id="deleteForm{{ $datum->id }}" action="{{ route('admin.event.destroy', $datum->id) }}" method="POST">
                                                @csrf
                                                @method('delete')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script>
        $(function () {
            $('.eventTable').dataTable({
                dom: 'Bfrtip',
                responsive: true,
                buttons: [
                    // 'copy', 'csv', 'excel', 'pdf', 'print',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },

                ],
                order: [3, 'desc']
            });
        });
        function deleteData(id) {
            swal({
                title: 'Are you sure?',
                icon: "warning",
                buttons: {
                    cancel: true,
                    confirm: true,
                },
            }).then( willDelete => {
                if(willDelete){
                    $('#deleteForm'+id).submit();
                }
            });
        }
    </script>
@endpush

resources/views/admin/event/show.blade.php
@extends('layouts.backend.app')

@section('title', 'Event detail')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.event.index') }}"><i class="material-icons">event</i>Event list</a></li>
                <li class="active"><i class="material-icons">remove_red_eye</i> View event detail</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2 class="text-capitalize">
                            {{ $event->name }}
                            <small>
                                <i class="material-icons" style="font-size: small">place</i>
                                {{ $event->address }}
                            </small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li>
                                <b>Date:</b>
                                {{ date('M d, Y', strtotime($event->date)) }}
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        {!! html_entity_decode($event->description) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')

@endpush