routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('category', 'CategoryController');
    Route::resource('resort', 'ResortController', ['only' => ['show', 'index', 'destroy', 'update']]);
    Route::resource('event', 'EventController');
    Route::resource('tourist', 'TouristController');
    Route::resource('archive', 'ArchiveController');
    Route::resource('hotline', 'HotlineController', ['except' => ['show']]);
    Route::resource('profile', 'ProfileController');
    Route::resource('account', 'AccountController');
});

Route::group(['as' => 'owner.', 'prefix' => 'owner', 'namespace' => 'Owner', 'middleware' => ['auth', 'owner']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('resort', 'ResortController');
    Route::resource('image', 'ImageController');
    Route::post('image/remove','ImageController@fileDestroy')->name('image.remove');
    Route::post('image/upload/{image}','ImageController@upload')->name('image.upload');
    Route::resource('profile', 'ProfileController');
});

app/Http/Controllers/Admin/TouristController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Category;
use App\Model\Tourist;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TouristController extends Controller
{

    public function index()
    {
        $data = Tourist::query()
            ->latest('updated_at')
            ->get();
        return view('admin.tourist.index',[
            'tourists' => $data
        ]);
    }

    public function create()
    {
        $data = Category::all();
        return view('admin.tourist.create',[
            'data' => $data
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'categories' => 'required',
            'description' => 'required',
        ]);

        $tourist = new Tourist();
        $tourist->name = $request->name;
        $tourist->slug = str_slug($request->title);
        $tourist->address = $request->address;
        $tourist->description = $request->description;
        $tourist->save();

        $tourist->categories()->attach($request->categories);

        Toastr::success('Successfully Saved' ,'Success');
        return redirect()->route('admin.tourist.index');
    }

    public function show(Tourist $tourist)
    {
        return view('admin.tourist.show',[
            'data' => $tourist
        ]);
    }

    public function edit(Tourist $tourist)
    {
        $categories = Category::all();
        return view('admin.tourist.edit',[
            'tourist' => $tourist,
            'categories' => $categories
        ]);
    }

    public function update(Request $request, Tourist $tourist)
    {
        $this->validate($request, [
            'name' => 'required',
            'address' => 'required',
            'categories' => 'required',
            'description' => 'required',
        ]);

        $tourist->name = $request->name;
        $tourist->slug = str_slug($request->title);
        $tourist->address = $request->address;
        $tourist->description = $request->description;
        $tourist->save();

        $tourist->categories()->sync($request->categories);

        Toastr::success('Successfully Updated' ,'Success');
        return redirect()->route('admin.tourist.index');
    }

    public function destroy(Tourist $tourist)
    {
        Tourist::destroy($tourist->id);
        Toastr::success('Successfully Deleted' ,'Success');
        return redirect()->route('admin.tourist.index');
    }
}

resources/views/admin/tourist/create.blade.php
@extends('layouts.backend.app')

@section('title', 'Create tourist')

@push('css')
    <!-- Bootstrap Select Css -->
    <link href="{{ asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.tourist.index') }}"><i class="material-icons">map</i>Tourist spot list</a></li>
                <li class="active"><i class="material-icons">create</i> Create tourist</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>ADDING TOURIST SPOT</h2>
                    </div>
                    <div class="body">
                        <form id="tourist_form" action="{{ route('admin.tourist.store') }}" method="POST">
                            @csrf
                            <div class="row clearfix">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label>Event name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="tourist_form_name" name="name" placeholder="Event name" value="{{ old('name') }}" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Address</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="tourist_form_address" name="address" value="{{ old('address') }}" placeholder="Address">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Event date</label>
                                        <div class="form-line">
                                            <select name="categories[]" id="category" class="form-control show-tick" data-live-search="true" multiple>
                                                @foreach($data as $category)
                                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="tourist_form_description">Description</label>
                                        <div class="form-line">
                                            <textarea class="form-control" id="tourist_form_description" name="description" placeholder="Description">{{ old('description') }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <!-- Select Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <script>
        $('#tourist_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'address': {
                    required: true,
                },
                'date': {
                    required: true,
                },
                'description': {
                    required: true,
                },
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/tourist/edit.blade.php
@extends('layouts.backend.app')

@section('title', 'Create tourist')

@push('css')
    <!-- Bootstrap Select Css -->
    <link href="{{ asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.tourist.index') }}"><i class="material-icons">map</i>Tourist spot list</a></li>
                <li class="active"><i class="material-icons">create</i> Edit tourist</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>EDIT TOURIST SPOT</h2>
                    </div>
                    <div class="body">
                        <form id="tourist_form" action="{{ route('admin.tourist.update', $tourist->id) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="row clearfix">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Tourist spot name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="tourist_form_name" name="name" placeholder="Event name"
                                                   value="{{ $tourist->name }}" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Address</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" id="tourist_form_address" name="address" placeholder="Address"
                                                   value="{{ $tourist->address }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="category">Categories</label>
                                        <div class="form-line">
                                            <select name="categories[]" id="category" class="form-control show-tick" data-live-search="true" multiple>
                                                @foreach($categories as $category)
                                                    <option
                                                        @foreach($tourist->categories as $touristCategory)
                                                            {{ $touristCategory->id == $category->id ? 'selected' : '' }}
                                                        @endforeach
                                                        value="{{ $category->id }}" >{{ $category->name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="tourist_form_description">Description</label>
                                        <div class="form-line">
                                            <textarea class="form-control" rows="10" id="tourist_form_description" name="description" placeholder="Description">{{ $tourist->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <!-- Select Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <script>
        $('#tourist_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'address': {
                    required: true,
                },
                'date': {
                    required: true,
                },
                'description': {
                    required: true,
                },
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/tourist/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Event')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.tourist.index') }}"><i class="material-icons">map</i>Tourist spot list</a></li>
            </ol>
        </div>

        <!-- Content -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            TOURISTS SPOT LIST
                            <label class="label label-info">{{ $tourists->count() }}</label>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="{{ route('admin.tourist.create') }}" class="btn bg-teal waves-effect">
                                    ADD TOURIST SPOT
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover touristTable">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Categories</th>
                                    <th>Address</th>
                                    <th>Updated at</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($tourists as $key => $datum)
                                    <tr>
                                        <td>{{ str_limit($datum->name, 20) }}</td>
                                        <td>
                                            @foreach($datum->categories as $category)
                                                <span class="label bg-teal">{{ $category->name }}</span>
                                            @endforeach
                                        </td>
                                        <td class="text-capitalize">{{ $datum->address }}</td>
                                        <td width="170px">{{ date('M d, Y h:i:s A', strtotime($datum->updated_at)) }}</td>
                                        <td width="150px">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Action <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="{{ route('admin.tourist.show', $datum->id) }}">
                                                            <i class="material-icons">remove_red_eye</i>View
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="{{ route('admin.tourist.edit', $datum->id) }}">
                                                            <i class="material-icons">edit</i>Edit
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:void(0)" onclick="deleteData({{ $datum->id }})">
                                                            <i class="material-icons">delete</i>Delete
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <form id="deleteForm{{ $datum->id }}" action="{{ route('admin.tourist.destroy', $datum->id) }}" method="POST">
                                                @csrf
                                                @method('delete')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script>
        $(function () {
            $('.touristTable').dataTable({
                dom: 'Bfrtip',
                responsive: true,
                buttons: [
                    // 'copy', 'csv', 'excel', 'pdf', 'print',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },

                ],
                order: [3, 'desc']
            });
        });
        function deleteData(id) {
            swal({
                title: 'Are you sure?',
                icon: "warning",
                buttons: {
                    cancel: true,
                    confirm: true,
                },
            }).then( willDelete => {
                if(willDelete){
                    $('#deleteForm'+id).submit();
                }
            });
        }
    </script>
@endpush

resources/views/admin/tourist/show.blade.php
@extends('layouts.backend.app')

@section('title', 'Event detail')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.tourist.index') }}"><i class="material-icons">map</i>Tourist spot list</a></li>
                <li class="active"><i class="material-icons">remove_red_eye</i> View tourist spot detail</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2 class="text-capitalize">
                            {{ $data->name }}
                            <small>
                                <i class="material-icons" style="font-size: small">place</i>
                                {{ $data->address }}
                            </small>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="{{ route('admin.tourist.edit', $data->id) }}" class="btn btn-info
                                 waves-effect">
                                    Edit
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        {!! html_entity_decode($data->description) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')

@endpush