routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('category', 'CategoryController');
    Route::resource('resort', 'ResortController', ['only' => ['show', 'index', 'destroy', 'update']]);
    Route::resource('event', 'EventController');
    Route::resource('tourist', 'TouristController');
    Route::resource('archive', 'ArchiveController');
    Route::resource('hotline', 'HotlineController', ['except' => ['show']]);
    Route::resource('profile', 'ProfileController');
    Route::resource('account', 'AccountController');
});

Route::group(['as' => 'owner.', 'prefix' => 'owner', 'namespace' => 'Owner', 'middleware' => ['auth', 'owner']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('resort', 'ResortController');
    Route::resource('image', 'ImageController');
    Route::post('image/remove','ImageController@fileDestroy')->name('image.remove');
    Route::post('image/upload/{image}','ImageController@upload')->name('image.upload');
    Route::resource('profile', 'ProfileController');
});

app/Http/Controllers/Admin/HotlineController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Hotline;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HotlineController extends Controller
{

    public function index()
    {
        $hotlines = Hotline::query()
            ->latest('updated_at')
            ->get();
        return view('admin.hotline.index', [
            'hotlines' => $hotlines
        ]);
    }

    public function create()
    {
        return view('admin.hotline.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'number' => 'required',
        ]);

        $hotline = new Hotline();
        $hotline->name = $request->name;
        $hotline->number = $request->number;
        $hotline->save();

        Toastr::success('Successfully Saved' ,'Success');
        return redirect()->route('admin.hotline.index');
    }

    public function edit(Hotline $hotline)
    {
        return view('admin.hotline.edit',[
            'hotline' => $hotline
        ]);
    }

    public function update(Request $request, Hotline $hotline)
    {
        $this->validate($request, [
            'name' => 'required',
            'number' => 'required',
        ]);

        $hotline->name = $request->name;
        $hotline->number = $request->number;
        $hotline->save();

        Toastr::success('Successfully Updated' ,'Success');
        return redirect()->route('admin.hotline.index');
    }

    public function destroy(Hotline $hotline)
    {
        $hotline::destroy($hotline->id);
        Toastr::success('Successfully Deleted' ,'Success');
        return redirect()->route('admin.hotline.index');
    }
}

resources/views/admin/hotline/create.blade.php
@extends('layouts.backend.app')

@section('title', 'Create Hotline')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.hotline.index') }}"><i class="material-icons">map</i>Hotline list</a></li>
                <li class="active"><i class="material-icons">create</i> Create hotline</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>CREATE HOTLINE</h2>
                    </div>
                    <div class="body">
                        <form id="hotline_form" action="{{ route('admin.hotline.store') }}" method="POST">
                            @csrf
                            <div class="row clearfix">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Contact name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" name="name" placeholder="Contact name" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Telephone no.</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" name="number" placeholder="Telephone no.">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <script>
        $('#hotline_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'number': {
                    required: true,
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/hotline/edit.blade.php
@extends('layouts.backend.app')

@section('title', 'Create hotline')

@push('css')

@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.hotline.index') }}"><i class="material-icons">call</i>Hotline list</a></li>
                <li class="active"><i class="material-icons">create</i> Edit hotline</li>
            </ol>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>EDIT HOTLINE</h2>
                    </div>
                    <div class="body">
                        <form id="hotline_form" action="{{ route('admin.hotline.update', $hotline->id) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="row clearfix">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Hotline name</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" name="name" placeholder="Hotline name" value="{{ $hotline->name }}" autofocus>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Number</label>
                                        <div class="form-line">
                                            <input type="text" class="form-control text-capitalize" name="number" placeholder="number" value="{{ $hotline->number }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <script>
        $('#hotline_form').validate({
            rules: {
                'name': {
                    required: true,
                },
                'number': {
                    required: true,
                }
            },
            highlight: function (input) {
                $(input).parents('.form-line').addClass('error');
            },
            unhighlight: function (input) {
                $(input).parents('.form-line').removeClass('error');
            },
            errorPlacement: function (error, element) {
                $(element).parents('.input-group').append(error);
                $(element).parents('.form-group').append(error);
            }
        });
    </script>
@endpush

resources/views/admin/hotline/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Hotline')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <ol class="breadcrumb breadcrumb-col-teal">
                <li><a href="{{ route('admin.hotline.index') }}"><i class="material-icons">call</i>Hotlines list</a></li>
            </ol>
        </div>

        <!-- Content -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            HOTLINES LIST
                            <label class="label label-info">{{ $hotlines->count() }}</label>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="{{ route('admin.hotline.create') }}" class="btn bg-teal waves-effect">
                                    ADD HOTLINE
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover hotlineTable">
                                <thead>
                                <tr>
                                    <th>Contact name</th>
                                    <th>Telephone no.</th>
                                    <th>Updated at</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($hotlines as $key => $datum)
                                    <tr>
                                        <td>{{ str_limit($datum->name, 50) }}</td>
                                        <td width="120px">{{ $datum->number }}</td>
                                        <td width="170px">{{ date('M d, Y h:i:s A', strtotime($datum->updated_at)) }}</td>
                                        <td width="150px">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Action <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="{{ route('admin.hotline.edit', $datum->id) }}">
                                                            <i class="material-icons">edit</i>Edit
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascript:void(0)" onclick="deleteData({{ $datum->id }})">
                                                            <i class="material-icons">delete</i>Delete
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <form id="deleteForm{{ $datum->id }}" action="{{ route('admin.hotline.destroy', $datum->id) }}" method="POST">
                                                @csrf
                                                @method('delete')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script>
        $(function () {
            $('.hotlineTable').dataTable({
                dom: 'Bfrtip',
                responsive: true,
                buttons: [
                    // 'copy', 'csv', 'excel', 'pdf', 'print',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [ 0, 1, 2 ]
                        }
                    },

                ],
                order: [3, 'desc']
            });
        });
        function deleteData(id) {
            swal({
                title: 'Are you sure?',
                icon: "warning",
                buttons: {
                    cancel: true,
                    confirm: true,
                },
            }).then( willDelete => {
                if(willDelete){
                    $('#deleteForm'+id).submit();
                }
            });
        }
    </script>
@endpush